/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plugin1;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ANTONIO
 */
public class DialogoAddClientes extends javax.swing.JDialog {

    java.awt.Frame mParent;
    Factura mFactura;
    boolean isPrimero=false;
    
    /**
     * Creates new form DialogoClientes
     * @param parent
     * @param modal
     * @param bundle
     */
    public DialogoAddClientes(java.awt.Frame parent, boolean modal,  Factura oFactura, int iDisponible) {
        super(parent, modal);
        mFactura=oFactura;
        oModelo = new ModeloAddClientes(parent);
        if (oFactura.getUnidades()-iDisponible==0){
            isPrimero=true;
        }
        mParent=parent;
        initComponents();
        this.setBackground(parent.getBackground());
        this.repaint();
        this.setResizable(false);
        cambiarIdioma();
        llenarTabla();
    }
    
    
    
    
    
    private void cambiarIdioma(){
        //para el menu
        this.setTitle("Search Client");
        etiquetaBuscar.setText("Search:");
        checkSoloInactivos.setText("Only Inactives Clients");
        
    }
    
    private void llenarTabla(){
        oModelo.llenarTabla("%", checkSoloInactivos.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        etiquetaBuscar = new javax.swing.JLabel();
        textBusqueda = new javax.swing.JTextField();
        checkSoloInactivos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setForeground(new java.awt.Color(255, 255, 51));

        tablaClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaClientes.setModel(oModelo);
        tablaClientes.setRowHeight(35);
        tablaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editar(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        etiquetaBuscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaBuscar.setText("Buscar:");

        textBusqueda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtrar(evt);
            }
        });

        checkSoloInactivos.setSelected(true);
        checkSoloInactivos.setText("Sin Huella");
        checkSoloInactivos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                filtrarSinHuella(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkSoloInactivos)
                        .addGap(0, 661, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textBusqueda)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiquetaBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(checkSoloInactivos)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtrar
        // TODO add your handling code here:
        oModelo.llenarTabla(textBusqueda.getText().trim().toUpperCase(), checkSoloInactivos.isSelected());
    }//GEN-LAST:event_filtrar

    private void editar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            try {
                Cliente oCliente = new Cliente(mParent);
                if (isPrimero && oCliente.esGrupal(((Cliente) this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(), ModeloClientes.COL_CLIENTE)).getCodCliente())) {
                    int confirmado = JOptionPane.showConfirmDialog(this, "This client belongs to a group. Do you want to load all the clients associated with the group?");
                    if (JOptionPane.OK_OPTION == confirmado) {
                        oCliente.copiarGrupo();
                        dispose();
                    }else{
                        mFactura.addClient(mParent, ((Cliente) this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(), ModeloClientes.COL_CLIENTE)).getCodCliente());
                    }
                }else{
                    mFactura.addClient(mParent, ((Cliente) this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(), ModeloClientes.COL_CLIENTE)).getCodCliente());
                }
                dispose();
                //aqui agrego a las personas
                //abrirDialogoInscripcion((Cliente)this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(),ModeloClientes.COL_CLIENTE));
            } catch (SQLException ex) {
                Util.guardarError(ex, true);
            }
        }
    }//GEN-LAST:event_editar

    private void filtrarSinHuella(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_filtrarSinHuella
        // TODO add your handling code here:
        //llenarTabla();
    }//GEN-LAST:event_filtrarSinHuella

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkSoloInactivos;
    private javax.swing.JLabel etiquetaBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField textBusqueda;
    // End of variables declaration//GEN-END:variables

    private final ModeloAddClientes oModelo;
    

}

