/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plugin1;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class DialogoClientes extends javax.swing.JDialog {
    
    Factura mFactura;
    private int iDiponibles;
    java.awt.Frame mParent;

    /**
     * Creates new form DialogoClientes
     * @param parent
     * @param modal
     * @param oFactura
     */
    public DialogoClientes(java.awt.Frame parent, boolean modal, Factura oFactura) {
        super(parent, modal);
        oModelo = new ModeloClientes(parent);
        try {
            mFactura=oFactura;
            iDiponibles=oFactura.getUnidades()-oFactura.getCantidadClientesFactura(parent);
            
            mParent=parent;
            initComponents();
            this.setBackground(parent.getBackground());
            this.repaint();
            this.setResizable(false);
            actualizarBoton(0);
            oModelo.llenarTabla(oFactura);
        } catch (SQLException ex) {
            Util.guardarError(ex, true,parent);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        botonAgregar = new javax.swing.JButton();
        botonRemover = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        etiquetaDisponibles = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Clientes");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(593, 629));
        setMinimumSize(new java.awt.Dimension(593, 629));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Clientes Disponibles:");

        tablaClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablaClientes.setModel(oModelo);
        tablaClientes.setRowHeight(40);
        jScrollPane1.setViewportView(tablaClientes);

        botonAgregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonAgregar.setText("Agregar Cliente");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonRemover.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonRemover.setText("Quitar Cliente");
        botonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverActionPerformed(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        etiquetaDisponibles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaDisponibles.setForeground(new java.awt.Color(0, 51, 204));
        etiquetaDisponibles.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(botonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 66, Short.MAX_VALUE)
                                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaDisponibles)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiquetaDisponibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void actualizarBoton(int iCantidad){
        iDiponibles=iDiponibles+iCantidad;
        etiquetaDisponibles.setText(String.valueOf(iDiponibles));
        if(iDiponibles==0){
            botonAceptar.setEnabled(true);
            botonAgregar.setEnabled(false);
        }else{
            botonAceptar.setEnabled(false);
            botonAgregar.setEnabled(true);
        }
            
    }
    private void botonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverActionPerformed
        // TODO add your handling code here:
        try{
            int confirmado = JOptionPane.showConfirmDialog(this, "Do you want to delete the selected client?");
            if (JOptionPane.OK_OPTION == confirmado) {
                mFactura.removeClient(mParent, ((Cliente)this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(),ModeloClientes.COL_CLIENTE)).getCodCliente());
                oModelo.llenarTabla(mFactura);
                
                actualizarBoton(1);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "You must select a client.",
                    "Message",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRemoverActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        try {

            if (dialogoAddClientes == null) {

                dialogoAddClientes = new DialogoAddClientes(mParent,true, mFactura,iDiponibles);
                dialogoAddClientes.setLocationRelativeTo(this);
            }
            dialogoAddClientes.setVisible(true);
            dialogoAddClientes = null;
            oModelo.llenarTabla(mFactura);
            iDiponibles=mFactura.getUnidades()-mFactura.getCantidadClientesFactura(mParent);
            actualizarBoton(0);
        } catch (Exception ex) {
            Util.guardarError(ex, true, this);
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        int confirmado = JOptionPane.showConfirmDialog(this, "Press Yes to continue or No to cancel");
        if (JOptionPane.OK_OPTION == confirmado) {
            dispose();
        }


    }//GEN-LAST:event_botonAceptarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonRemover;
    private javax.swing.JLabel etiquetaDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables

    private final ModeloClientes oModelo;
    DialogoAddClientes dialogoAddClientes;
}
